name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:13
          - gcc:12
          - gcc:11
          - gcc:10
          - clang:17
          - clang:16
          - clang:15
          - clang:14
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_analyse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - valgrind
          - flawfinder
    container:
      image: "registry.gitlab.com/offa/docker-images/gcc:13"
    name: "${{ matrix.tool }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh -${{ matrix.tool }}

  formatting-check:
    name: "formatting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DoozyX/clang-format-lint-action@master
      name: "Verify formatting"
      with:
        clangFormatVersion: 15
