name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - gcc-11
          - gcc-10
          - gcc-9
          - gcc-8
          - clang-13
          - clang-12
          - clang-11
          - clang-10
          - clang-9
          - clang-8
          - clang-7
    container:
      image: "registry.gitlab.com/offa/docker-images-ci/dist-keygen/${{ matrix.compiler }}:latest"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_analyse:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tool:
          - valgrind
          - flawfinder
    container:
      image: "registry.gitlab.com/offa/docker-images-ci/dist-keygen/gcc-10:latest"
    name: "Analyse ${{ matrix.tool }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh -${{ matrix.tool }}
